# Generated by Django 4.1.3 on 2022-11-09 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0004_alter_meal_category_alter_meal_main_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='administrative',
            options={'verbose_name': 'Chef'},
        ),
        migrations.AddField(
            model_name='tabledetail',
            name='table_image',
            field=models.ImageField(blank=True, null=True, upload_to='Table'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='category',
            field=models.CharField(choices=[('Fast_Food', 'Fast Food'), ('Break_Fast', 'Break Fast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner')], default='Select', max_length=30),
        ),
        migrations.AlterField(
            model_name='meal',
            name='main_category',
            field=models.CharField(choices=[('vage', 'Veg Food'), ('nonvage', 'Non Veg Food')], default='Select', max_length=30),
        ),
    ]
